### ISSUE TITLE
two-steps reconstruction approach

### ISSUE THREAD

**Issue by fujch7** [amkozlov/raxml-ng#104]
Hi developers,

Is this a two-step tree building method like raxml? by deriving the first phylogeny with any of the available approaches and then refine it in a second step using RAxML.

Many thanks!

**Comment by amkozlov** [comment]
Well you can specify your first-step phylogeny as a starting tree via `--tree` option. In some cases, it can decrease tree inference time, but also increase the risk of hitting a local optimum. In general, there is no guarantee that a "better" starting tree leads to a better-scoring final ML tree. We therefore recommend using multiple distinct starting, which is now the default in RAxML-NG.

**Comment by amkozlov** [comment]
closing since the question was answered
