### ISSUE TITLE
Installation with conda

### ISSUE THREAD

**Issue by cmorganl** [amkozlov/raxml-ng#105]
Hi Alexey,

I was wondering if there was someone actively maintaining the conda build recipe for RAxML-NG and if so, whether they could trigger an update? The conda version is still at v0.9.0 and I'm sure there are loads of people (like me) that would love to have the latest available!

Thanks!
Connor

**Comment by amkozlov** [comment]
Hi Connor,

as I learned today there is no such thing as "conda recipe  maintainer" :) but rather, everyone can add/update recipes by submitting PRs.

So it tried to do it myself, but wasn't successful so far:

https://github.com/bioconda/bioconda-recipes/pull/24522

Best,
Alexey

**Comment by cmorganl** [comment]
Sorry for any confusion, I just didn't want to step on someone's toes by trying to update it myself!

Glad to see you and Pierre are updating it though. I hope you're able to figure out any failing tests quickly and easily.

Thanks again!
Connor

**Comment by amkozlov** [comment]
Hi Connor,

with the kind help of @Pbdas, raxml-ng conda package is now at v1.0.1!

Best,
Alexey

**Comment by cmorganl** [comment]
That's great news. Huge thanks to you and Pierre!
