### ISSUE TITLE
Tree reporting with --all

### ISSUE THREAD

**Issue by NatJWalker-Hale** [amkozlov/raxml-ng#107]
Based on the log reporting, under `--all` raxml-ng first completes all 20 ML tree searches, and then begins bootstrapping. I wonder if it would be possible to write the trees from each search (and the best ML tree) to the output file at this stage, and not only at the completion of the entire bootstrapping analysis? This would be helpful for checkpointing if the run is accidentally killed during bootstrapping. 

If there is already a way to extract the trees at this stage and I have missed it, many apologies. 

Thanks in advance, 

Nat

**Comment by amkozlov** [comment]
Dear Nat,

with the newest version (1.0+), intermediate results are printed into respective `*.TMP` files, please see:

https://github.com/amkozlov/raxml-ng/wiki/Output:-files-and-settings#output-files

In addition, search state is periodically saved to a checkpoint file, so you can resume a killed/interrupted run by simply issuing the same raxml-ng command again.

**Comment by NatJWalker-Hale** [comment]
Dear @amkozlov 

Thanks, that's perfect! I hadn't realised but I was still on 0.9, so I will update accordingly. 

Best, 

Nat
