### ISSUE TITLE
Could not see bootstrap values on .bestTree

### ISSUE THREAD

**Issue by Niv94** [amkozlov/raxml-ng#110]
Hi,
I am a graduate student running RaxML for my SNP dataset

I recently did a "ML + thorough bootstrap + consensus" analysis in RaxmlGUI using Raxml-ng. As outputs - I got a “.bestTree” and “.bootstraps” files. I tried to open the .bestTree file in FigTree and I did not see the bootstrap values on the tree. Am I doing something wrong? Could you please guide me?

Thank you so much,
Nivi

**Comment by amkozlov** [comment]
Hi Nivi,

with a standalone version of raxml-ng, bootstrap support values are printed into `.supportTree` file, see:   https://github.com/amkozlov/raxml-ng/wiki/Output:-files-and-settings#output-files

Not sure how it works in raxmlGUI though, so if you have questions, please contact raxmlGUI developers directly:

https://github.com/AntonelliLab/raxmlGUI

Best,
Alexey

**Comment by Niv94** [comment]
Thank you so much. Yes the .support file works.

**Comment by amkozlov** [comment]
great!
