### ISSUE TITLE
Non-comprehensive constraint tree issue

### ISSUE THREAD

**Issue by zcalamari** [amkozlov/raxml-ng#114]
Hello,

I am trying to run RAxML-ng with a non-comprehensive constraint tree, but I keep getting this error:

[00:00:00] Loaded non-comprehensive constraint tree with 15 taxa
Assertion failed: (bin_tree->inner_count == old_inner_count + degree-3), function pllmod_utree_resolve_multi, file /Users/sco/alexey/raxml-ng/libs/pll-modules/src/tree/pll_tree.c, line 356.
zsh: abort      /Applications/raxml-ng_v0.9.0_macos_x86_64/raxml-ng --all --tree-constraint  

I have also tried running this on the CIPRES implementation and it also quits after the "[00:00:00] Loaded non-comprehensive constraint tree with 15 taxa" line. My constraint tree is a fully bifurcating newick tree that doesn't have all the species in it. 

Any help would be appreciated!

**Comment by amkozlov** [comment]
could you please post your constraint tree file and full raxml-ng log here?

**Comment by zcalamari** [comment]
I have attached both, thanks!

[RAxML.output.txt](https://github.com/amkozlov/raxml-ng/files/5958742/RAxML.output.txt)

[NewickExtantCollapsedBackboneTree.txt](https://github.com/amkozlov/raxml-ng/files/5958750/NewickExtantCollapsedBackboneTree.txt)

**Comment by amkozlov** [comment]
For some reason, your tree had an extra pair of parenthesis around of the clades. Please find fixed tree attached.

Also, I strongly recommend to upgrade raxml-ng to the most recent version. 

[tree3.txt](https://github.com/amkozlov/raxml-ng/files/5960688/tree3.txt)

**Comment by zcalamari** [comment]
Thanks for the support! I was planning to run this on CIPRES and was using my local install to troubleshoot when the CIPRES version wasn't working. Will update regardless.

**Comment by amkozlov** [comment]
OK from now on, raxml-ng will print a meaningful error message in such cases.

So I guess this issue is resolved?

**Comment by zcalamari** [comment]
Yes, thank you!
