### ISSUE TITLE
Assertion `xguess[p] >= xmin && xguess[p] <= xmax' failed error message

### ISSUE THREAD

**Issue by mjgomez12** [amkozlov/raxml-ng#115]
Hi, 

I am trying to use raxml-ng for phylogenetic reconstruction of a set of chloroplasts. When I run it I get the following error:

`[00:00:00] NOTE: Resuming execution from checkpoint (logLH: -327888.58, ML trees: 16, bootstraps: 0)
[00:00:00] Data distribution: max. partitions/sites/weight per thread: 3 / 761 / 12128

Starting ML tree search with 20 distinct starting trees

[00:00:00 -327888.581464] SPR radius for FAST iterations: 20 (autodetect)
[00:00:00 -327888.581464] SLOW spr round 7 (radius: 15)
raxml-ng: /opt/conda/conda-bld/raxml-ng_1569616353378/work/libs/pll-modules/src/optimize/pll_optimize.c:1548: recomp_iterative_multi: Assertion `xguess[p] >= xmin && xguess[p] <= xmax' failed.
raxml-ng: /opt/conda/conda-bld/raxml-ng_1569616353378/work/libs/pll-modules/src/optimize/pll_optimize.c:1548: recomp_iterative_multi: Assertion `xguess[p] >= xmin && xguess[p] <= xmax' failed.
bash-tree: line 1: 94101 Aborted                 (core dumped) raxml-ng --msa all-concatenated-only-natural.fa --model modeltest-output.part.aic --seed 2 --threads 2
`

I don't know what might be causing this. 

Any help is much appreciate it!

**Comment by amkozlov** [comment]
@mjgomez12 thanks for reporting! could you please post full raxml-ng log file, and if possible, your input files (`all-concatenated-only-natural.fa` and `modeltest-output.part.aic`)?

**Comment by amkozlov** [comment]
If the issue still exists, please reopen.
