### ISSUE TITLE
RogueNaRok implementation

### ISSUE THREAD

**Issue by PiraMew** [amkozlov/raxml-ng#118]
Hello, 
I would like to detect rogue taxa using RogueNaRok.
I am wondering if RAxML-ng implements this tool like the previous one that I can run something like `/path/to/raxmlHPC-SSE3 -z RnR-prune_prunedBootstraps.reduced  -m GTRCAT -J MR -n tmp`?

**Comment by amkozlov** [comment]
I understand that you want to build a consensus tree, this option is available in raxml-ng as well:

https://github.com/amkozlov/raxml-ng/wiki/Consensus-tree-building

**Comment by amkozlov** [comment]
@PiraMew if you have further questions, please use our user support group:

https://groups.google.com/g/raxml
