### ISSUE TITLE
Suddenly Stop of RAxML-NG with no error

### ISSUE THREAD

**Issue by herongzju** [amkozlov/raxml-ng#127]
Hi,
I tried twice to run RAxML-NG using a partitioned dataset. But over a half month, the procedure suddenly stop without generating besttree. see the attached file.

Thank you!
[raxmlng_uce50.raxml.log](https://github.com/amkozlov/raxml-ng/files/7215941/raxmlng_uce50.raxml.log)

**Comment by amkozlov** [comment]
would you mind sharing your input files?

as a quick workaround, you can try to restart raxml-ng with exactly the same command line (ie resuming from a checkpoint), this sometimes circumvents the errors,,,

**Comment by herongzju** [comment]
Thanks for your reply! the command lines is raxml-ng --msa uce50_supermatrix.phy --prefix raxmlng_uce --model uce50_supermatrix_partition.txt --outgroup Dmel,Dnov --threads 23 -all --force --bs-trees 1000. 
input files in  the attached file.

**Comment by amkozlov** [comment]
@herongzju sorry but I haven't received any files from you, I also checked the spam folder. You can also archive all files and attach zip/tgz file, I guess this is allowed here.

**Comment by amkozlov** [comment]
If the issue still exists, please reopen.
