### ISSUE TITLE
 CPU core oversubscription error, detecting more cores than being given!

### ISSUE THREAD

**Issue by Lamm-a** [amkozlov/raxml-ng#128]
Thanks for making a fantastic ML tree inference tool!
I am running RAML-NG on a tourque based cluster and am getting this error for some runs of the tool. I am using the following command: 

`raxml-ng --all --msa ${alignment} --model GTR+G --prefix ${prefix} --seed 2 --threads auto --bs-metric fbp,tbe`

With my Tourque submission allowing only 3 threads in a single node. Would the use of `--threads auto` be the cause for this error. if so why would it only happen sometimes?

**Comment by amkozlov** [comment]
I assume the problem is solved.
