### ISSUE TITLE
support unlinked branch lengths for partitioned alignments

### ISSUE THREAD

**Issue by amkozlov** [amkozlov/raxml-ng#13]
(RAxML -M option)

**Comment by stamatak** [comment]
Need to be careful here, such that branch lengths still refer to a mean subst. rate of 1.0, remember that respective nasty RAxML/ExaML bug I had to fix

**Comment by amkozlov** [comment]
implemented in https://github.com/amkozlov/raxml-ng/commit/4c3892f5d5f8d319fa9bc12fc3172ef814299602
