### ISSUE TITLE
CATG file --prob-msa on -- all branch lengths are 0.1

### ISSUE THREAD

**Issue by nehlehk** [amkozlov/raxml-ng#131]
When I'm using the probabilistic alignment (CATG file), it doesn't care about the probability value for each nucleotide; in all scenarios, the branch lengths are 0.1. Also, it doesn't matter what is the model option (--opt-branches on/off, --blopt: anything), the output tree is the same all the time.

**Comment by amkozlov** [comment]
fixed by 4c8b796
