### ISSUE TITLE
Overcome the error: Constraint check failed after SPR round!

### ISSUE THREAD

**Issue by padpadpadpad** [amkozlov/raxml-ng#147]
Hi raxml-ng team

I am trying to set topological constraints on the tree based on the taxonomic assignment of some of the tips. The alignment is 246bp for 3541 taxa.

The command I am running is: 

```
raxml-ng --msa alignment_myxo_97.7percent_new.fasta --model GTR+G --prefix myxo_97.7_constraint --threads 20 --seed 2 --outgroup otu_outgroup1 --tree-constraint contree.tre
```

However I am getting the error:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  ERROR in SPR round (LIBPLL-3584): Constraint check failed after SPR round!
Aborted (core dumped)
```

To us this hints that there is a problem with the constraint tree, but it is not obvious what this is. Any ideas what we could try to overcome this problem?

Many thanks
Dan

Attached is the non-comprehensive constraint tree and the sequence alignment. 

[Archive.zip](https://github.com/amkozlov/raxml-ng/files/9820069/Archive.zip)

**Comment by amkozlov** [comment]
Hi Dan,

apologies for the very late response. 

I just tried to reproduce with raxml-ng v 1.1.0, but the analysis ran to completion without errors.

Which version of raxml-ng have you used? Could you please attach full log file? 

Thanks,
Alexey

**Comment by amkozlov** [comment]
No problem, thanks for the confirmation!
