### ISSUE TITLE
TOO FEW SPECIES

### ISSUE THREAD

**Issue by Barrington-wustl** [amkozlov/raxml-ng#148]
Roary ran successfully as far as I can tell but now when I am running RAxML to make the phylogenic tree  

this is what I ran 

`(base) marshall@DESKTOP-LMRPD85:~$ raxmlHPC -s /home/marshall/Roary_Copy/Roary_Full/core_gene_alignment.aln -n Trikafta_Tree.txt -m GTRCAT -f a -x 123 -p 256 -N autoMRE -T 16
Use raxml with AVX support with overriden number of threads

RAxML can't, parse the alignment file as phylip file
it will now try to parse it as FASTA file

TOO FEW SPECIES`

is there something obvious that I am missing?

**Comment by Barrington-wustl** [comment]
I have 21 samples and I have seen this program run with less

**Comment by amkozlov** [comment]
Hello, please check that your input file is a valid PHYLIP or FASTA ailgnment. It looks like a formatting issue.

**Comment by amkozlov** [comment]
If the issue still exists, please post to the RAxML google group (note you are using standard-RAxML and not raxml-ng here).
