### ISSUE TITLE
Ascertainment Bias Correction

### ISSUE THREAD

**Issue by esteinig** [amkozlov/raxml-ng#15]
Thanks you so much for this amazing re-write, very much looking forward to using it. Is there any chance to implement the ascertainment bias correction options from RAxML?

**Comment by amkozlov** [comment]
Ascertainment bias correction is already available as of version 0.4.0.

You can use same models as in old good RAxML, namely:

Lewis: e.g.` --model GTR+G+ASC_LEWIS`

Felsenstein: e.g. `--model GTR+G+ASC_FELS{1000}`   // 1000 invariant sites

Stamatakis: e.g. `--model GTR+G+ASC_STAM{1000/2000/3000/4000}`   // 1000 invariant As, 2000 Cs, 3000 Gs, 4000 Ts

See also: https://github.com/amkozlov/raxml-ng/wiki/Input-data#evolutionary-model

Please let me know if there will be any problems/questions.

**Comment by esteinig** [comment]
My apologies for overlooking the Wiki entry - this is exactly it. Many thanks!

**Comment by amkozlov** [comment]
Great, so I will close this issue now.
