### ISSUE TITLE
run --start execution mode in parallel

### ISSUE THREAD

**Issue by tschuelia** [amkozlov/raxml-ng#151]
It would be nice if RAxML-NG would infer starting trees in parallel, either using the automated parallelization schema or a user provided number of threads :-)

**Comment by amkozlov** [comment]
Implemented in dev branch, please test.

**Comment by tschuelia** [comment]
Seems to work perfectly fine, thanks a lot for implementing this! :-)

**Comment by amkozlov** [comment]
this is now enabled by default in v1.2.0
