### ISSUE TITLE
Taxon names with invalid characters

### ISSUE THREAD

**Issue by AndreaAguadoM** [amkozlov/raxml-ng#153]
I obtain this error when trying to use this tool: 
ERROR: Following taxon name contains invalid characters:  ES02-660577
ERROR: Following taxon name contains invalid characters:  GASA770414M
ERROR: Following taxon name contains invalid characters:  TONA780704M
ERROR: Following taxon name contains invalid characters:  EPNU750606M
ERROR: Following taxon name contains invalid characters:  SUFE820420M
ERROR: Following taxon name contains invalid characters:  FEMO720622M
ERROR: Following taxon name contains invalid characters:  ES02-866741
ERROR: Following taxon name contains invalid characters:  SUGA740731M
ERROR: Following taxon name contains invalid characters:  ES02-22601
ERROR: Following taxon name contains invalid characters:  ES02-11376
ERROR: Following taxon name contains invalid characters:  ES02-76250
ERROR: Following taxon name contains invalid characters:  TOHE440602M
Which are the invalid characters?

**Comment by amkozlov** [comment]
could you please attach (part of) your alignment and full log file?

**Comment by amkozlov** [comment]
if the issue still exists, please reopen and provide the date I requested above
