### ISSUE TITLE
PARTITION FILE format - Error

### ISSUE THREAD

**Issue by vcastroagudin** [amkozlov/raxml-ng#154]
Hello Dr Lozlov,

I have some issues running Raxml-NG on Cipres. I am unsure if this is the correct place to write and ask for help, but I didn't find another option.

I used the format given in the manual of RaxML-NG for running the program on CIPRES Gateway, which gave me an error. Can it be possible that different models for DNA alignments with partition can be run on the RaxML lab website (https://raxml-ng.vital-it.ch/#/) but not in the cypres portal with the RanxMl-NG Black Box tool? 
Should the format of the files to indicate the alignment partition be different when the software is run on the website or CIPRES?

I used this syntax -entered as a txt file- to indicate my partition 
KY+I+G4, ITS = 1-561
TrNef+I+G4, TUB = 562-1053
HKY+I+G4, TEF = 1054-1565

And it gave me this error on CIPRES:

srun: error: exp-1-06: tasks 0-9: Exited with exit code 255
srun: launch/slurm: _step_signal: Terminating StepId=18453233.0

It did work on the website.
I really appreciate any help you can provide.
Thanks in advance,

Vanina

p.s.How do I subscribe to the google RaxML discussion group?

**Comment by amkozlov** [comment]
This question has been answered in the  RAxML google group:
https://groups.google.com/g/raxml/c/mGzUTGAXlbg/m/ecDs1dluAQAJ?utm_medium=email&utm_source=footer
