### ISSUE TITLE
Add bootstrap values to phylogenetic tree

### ISSUE THREAD

**Issue by asierFernandezP** [amkozlov/raxml-ng#155]
Hi,

I have ran raxml-ng using the following command, so I get the bootstrap confidence values in my phylogenetic tree:

`raxml-ng --all --msa $file --model GTR+G --tree pars{10} --bs-trees 100`

However, when I try to plot them I realised that the length of treeML$node.label (bootstrap values) is different to the length of treeML$tip.label, giving an error.

The code that I use is the following:

```
treeML <- read.tree(list.files("./", "support$")) # read tree
d <- data.frame(label=treeML$tip.label, bootstrap = treeML$node.label, pair_ID=pair_ID, Sample_type=Sample_type) #error raises here as lengths are different
```

Any solutions for this?

Thank you,
Asier

**Comment by amkozlov** [comment]
Hi Asier,

bootstrap support values are computed for inner nodes (or more precisely, for branches "above" the respective inner nodes). So why do yo expect. In a fully resolved unrooted tree with `n` tips, there are `n-2` inner nodes. So it is expected that `tip.label` and `node.label` have different sizes.

If you just want to plot a tree with support values in R, you do not need to remap anything, see an example here:

https://github.com/amkozlov/cellphy/blob/master/script/support-map.R

Best,
Alexey

**Comment by asierFernandezP** [comment]
Thank you very much for the explanation!

Best,
Asier
