### ISSUE TITLE
When I run raxml-ng v1.1, it stay in the stage of Starting ML tree search with 20 distinct starting trees for a longnight

### ISSUE THREAD

**Issue by Dkaaaaa** [amkozlov/raxml-ng#156]
Firstly, the check function is sucessfully performed with the following command:
raxml-ng --msa check-final-merge.min4.fasta --model TVM+I+G4 --check --prefix check

Then I run the following command to make the ML tree:
raxml-ng --msa check-final-merge.min4.fasta --model TVM+I+G4 --all --bs-trees 100 --threads 85 --prefix tree

Following is the log:
Analysis options:
  run mode: ML tree search + bootstrapping (Felsenstein Bootstrap)
  start tree(s): random (10) + parsimony (10)
  bootstrap replicates: 100
  random seed: 1676688219
  tip-inner: OFF
  pattern compression: ON
  per-rate scalers: OFF
  site repeats: ON
  branch lengths: proportional (ML estimate, algorithm: NR-FAST)
  SIMD kernels: AVX2
  parallelization: coarse-grained (auto), PTHREADS (85 threads), thread pinning: OFF

[00:00:00] Reading alignment from file: check-final-merge.min4.fasta
[00:00:00] Loaded alignment with 285 taxa and 228714 sites

Alignment comprises 1 partitions and 59569 patterns

Partition 0: noname
Model: TVM+FO+I+G4m
Alignment sites / patterns: 228714 / 59569
Gaps: 1.09 %
Invariant sites: 65.21 %

NOTE: Binary MSA file created: check-final-merge.min4.fasta.raxml.rba

Parallelization scheme autoconfig: 5 worker(s) x 17 thread(s)

Parallel reduction/worker buffer size: 1 KB  / 0 KB

[00:00:01] Generating 10 random starting tree(s) with 285 taxa
[00:00:01] Generating 10 parsimony starting tree(s) with 285 taxa
[00:00:31] Data distribution: max. partitions/sites/weight per thread: 1 / 3505 / 56080
[00:00:31] Data distribution: max. searches per worker: 24

Starting ML tree search with 20 distinct starting trees

Best wishes!

**Comment by amkozlov** [comment]
Please rerun with `--log debug` and post FULL log file here. Thank you!

Also, please make sure that you are using 1 thread per physical core:

https://github.com/amkozlov/raxml-ng/wiki/Parallelization
