### ISSUE TITLE
catg files/core dumped

### ISSUE THREAD

**Issue by gerhardJaeger** [amkozlov/raxml-ng#159]
When I try to run the precompiled linux-version of raxml-ng with a catg file, I get "core dumped". It does work when I compile the program from scratch.

Btw, the same problem also occurs with the anaconda version.

**Comment by amkozlov** [comment]
Thanks for reporting, this bug has been already fixed (#131), so the problem will be solved with the next release (v1.2).

**Comment by gerhardJaeger** [comment]
👍

**Comment by dlaehnemann** [comment]
Good to know, that this has been fixed, as I also ran into this. Will there be a release any time soon?

Would be very much appreciated, as I would prefer using the latest `bioconda` recipe for snakemake workflow integration, and currently I will have to implement a hacky workaround to get raxml-ng to automatically (and reproducibly) install in my workflow.

**Comment by amkozlov** [comment]
yes there will be a new release (v1.2) very soon, please stay tuned! ;)

**Comment by amkozlov** [comment]
So the new release which fixes this bug is now available:
https://github.com/amkozlov/raxml-ng/releases/tag/1.2.0

However, it is not yet in bioconda, and I'm not sure whether bioconda recipe will be updated automatically. I just recall last time I had to do it manually and it was a huge time waste, so help would be appreciated :)

**Comment by dlaehnemann** [comment]
Usually, the bioconda-bot should pick up the new version and automatically create a pull request with the necessary changes. But this hasn't happened, yet. So we might have to do this manually. But unless any dependencies changed (dropped or added), for such an update you should only ever have to:

1. Update the version number.
2. Update the sha256 hash value.
3. Reset the `build: number: ` to `0`.

But we could wait, whether the [update of the `conda-forge` version of the `bison` package to `3.8.2`](https://github.com/conda-forge/bison-feedstock/pull/31) works out. If it does, this should solve the [`libpll-2` compilation issue with `bison=3.8` from `conda-forge`](https://github.com/xflouris/libpll-2/issues/23) and we could in addition update the `bison`-dependency in the bioconda recipe to the minimum version of `bison =3.8.2`.

**Comment by amkozlov** [comment]
OK, waiting for review & merge:

https://github.com/bioconda/bioconda-recipes/pull/40931

**Comment by amkozlov** [comment]
Great, thanks for your help!
