### ISSUE TITLE
Bus Error on Apple M1 Ultra Using RAxML-NG v. 1.2.0

### ISSUE THREAD

**Issue by hushuzuiniu** [amkozlov/raxml-ng#168]
Dear all,

I encountered a bus error while running a Maximum Likelihood tree search with RAxML-NG on an Apple M1 Ultra system. The error occurred after the initial branch length optimization step. This issue arose despite running the program in FORCE mode, and I'm seeking assistance or suggestions for a resolution.

This is my running log:

> raxml-ng --model GTR+G4+FO --msa Alpha_3m_mask.fasta --seed 12345 --threads 4 --force --blmin 1e-10 --precision 16 --tree pars{1}
> 
> RAxML-NG v. 1.2.0 released on 09.05.2023 by The Exelixis Lab.
> Developed by: Alexey M. Kozlov and Alexandros Stamatakis.
> Contributors: Diego Darriba, Tomas Flouri, Benoit Morel, Sarah Lutteropp, Ben Bettisworth, Julia Haag, Anastasis Togkousidis.
> Latest version: https://github.com/amkozlov/raxml-ng
> Questions/problems/suggestions? Please visit: https://groups.google.com/forum/#!forum/raxml
> 
> System: Apple M1 Ultra, 20 cores, 128 GB RAM
> 
> RAxML-NG was called at 20-Dec-2023 17:16:02 as follows:
> 
> raxml-ng --model GTR+G4+FO --msa Alpha_3m_mask.fasta --seed 12345 --threads 4 --force --blmin 1e-10 --precision 16 --tree pars{1}
> 
> Analysis options:
>   run mode: ML tree search
>   start tree(s): parsimony (1)
>   random seed: 12345
>   tip-inner: OFF
>   pattern compression: ON
>   per-rate scalers: OFF
>   site repeats: ON
>   logLH epsilon: general: 10.000000, brlen-triplet: 1000.000000
>   fast spr radius: AUTO
>   spr subtree cutoff: 1.000000
>   fast CLV updates: ON
>   branch lengths: proportional (ML estimate, algorithm: NR-FAST)
>   SIMD kernels: SSE3
>   parallelization: coarse-grained (auto), PTHREADS (4 threads), thread pinning: OFF
> 
> WARNING: Running in FORCE mode: all safety checks are disabled!
> 
> [00:00:00] Reading alignment from file: Alpha_3m_mask.fasta
> [00:00:00] Loaded alignment with 7791 taxa and 29891 sites
> 
> Alignment comprises 1 partitions and 5141 patterns
> 
> Partition 0: noname
> Model: GTR+FO+G4m
> Alignment sites / patterns: 29891 / 5141
> Gaps: 1.23 %
> Invariant sites: 88.01 %
> 
> 
> NOTE: Binary MSA file created: Alpha_3m_mask.fasta.raxml.rba
> 
> Parallelization scheme autoconfig: 1 worker(s) x 4 thread(s)
> 
> [00:00:02] Generating 1 parsimony starting tree(s) with 7791 taxa
> Parallel parsimony with 4 threads
> Parallel reduction/worker buffer size: 1 KB  / 0 KB
> 
> [00:02:23] Data distribution: max. partitions/sites/weight per thread: 1 / 1286 / 20576
> [00:02:23] Data distribution: max. searches per worker: 1
> 
> Starting ML tree search with 1 distinct starting trees
> 
> [00:02:23 -6392907.1668888786807656] Initial branch length optimization
> zsh: bus error  raxml-ng --model GTR+G4+FO --msa Alpha_3m_mask.fasta --seed 12345 --threads 4

I would like to express my gratitude to the RAxML-NG team and the community for their continuous support and development efforts. Your work is greatly appreciated, and I am thankful for any assistance you can provide regarding this issue.

Best wishes,
Shu HU

**Comment by chenrui333** [comment]
check out this homebrew build, it works fine, https://github.com/Homebrew/homebrew-core/pull/132328

**Comment by chenrui333** [comment]
feel free to check out this latest release build as well, https://github.com/Homebrew/homebrew-core/pull/170510

**Comment by amkozlov** [comment]
I assume the problem has been solved with the homebrew build mentioned above -> closing.
