### ISSUE TITLE
can raxml-ng handle 6 million genomes of SARS-CoV-2?

### ISSUE THREAD

**Issue by liamxg** [amkozlov/raxml-ng#172]
Dear @amkozlov,

I have a dataset of 6 million genomes of SARS-CoV-2, can raxml-ng handle of this size?

**Comment by amkozlov** [comment]
Dear @liamxg ,

the short answer is: no :) 

For a detailed discussion, please read 
https://academic.oup.com/mbe/article/38/5/1777/6030946?login=false
and
https://academic.oup.com/mbe/article/39/12/msac254/6832260?login=false

**Comment by amkozlov** [comment]
Please read the papers I linked above.
If you do not find the answers there, please use our google group which is much better suited for such general questions:
https://groups.google.com/g/raxml
