### ISSUE TITLE
masked missing positions

### ISSUE THREAD

**Issue by TCHeaven** [amkozlov/raxml-ng#173]
I am running a multiple sequence alignment with DNA data, in my input fasta file some sequences contain 'N's at positions with missing data. How will raxml-ng handle this? Do I need to exclude these samples with missing data from the analysis?

**Comment by amkozlov** [comment]
Well raxml-ng will treat Ns as missing data, so you don;t have to exclude such samples because of raxml-ng.

Of course, you might still want to exclude some samples with "too much" missing data based on your filtering strategy.
