### ISSUE TITLE
tbe values when using a constraint tree

### ISSUE THREAD

**Issue by padpadpadpad** [amkozlov/raxml-ng#175]
Hi everyone

I am running raxml-ng with a constraint tree and it does everything I want for a single tree. I manually re-root the tree using figtree and all my monophyletic groups remain monophyletic. However I have some taxa that are allowed to be free across the tree.

However after I have bootstrapped the tree and calculated the tbe, I would have expected some nodes where my constraints were to have a value of 1, but this does not seem to be the case.

Is it because some of the nodes which can be free place differently so this split is not always containing exactly the same taxa.

Having read what the tbe means I think this is correct but would be good to sanity check myself.

Cheers
Dan

**Comment by amkozlov** [comment]
Hi Dan,

so based on your description it sounds reasonable. As long as TBE values for your "monophyletic" clades are high / close to 1, TBE is still doing what is supposed to: it prevents support from dropping low due to a few rogue taxa,
