### ISSUE TITLE
why the number is from #2 to #1?

### ISSUE THREAD

**Issue by BEAST-Community** [amkozlov/raxml-ng#178]
Dear @amkozlov,

<img width="503" alt="image" src="https://github.com/amkozlov/raxml-ng/assets/38597277/bc29164c-f8a8-49b2-a34f-bff4fdca55c6">

**Comment by amkozlov** [comment]
Tree searches from different starting trees are conducted in parallel, It can therefore happen than tree search #2 is completed before #1. This absolutely normal.

If for some reason you want all tree searches to be executed sequentially, just add `--workers 1` flag.
