### ISSUE TITLE
Substitution rates 

### ISSUE THREAD

**Issue by liamxg** [amkozlov/raxml-ng#182]
Dear @amkozlov,

What is the Substitution rates for each value? 

Substitution rates (ML): 0.077246 0.706620 0.177535 0.293354 2.188834 1.000000

**Comment by amkozlov** [comment]
The rates define upper triangle of the substitution matrix, e.g. for GTR the order is A-C, A-G, A-T, C-G, C-T, G-T.

Please see here for more details:
https://github.com/amkozlov/raxml-ng/wiki/Input-data#evolutionary-model
