### ISSUE TITLE
+B gets added to model description

### ISSUE THREAD

**Issue by wpfeiffer** [amkozlov/raxml-ng#186]
Hi,

I specified GTR+F+G as my DNA model, but RAxML-NG reported the following:

Partition 0: Subset1
Model: GTR+FC+G4m+B

Why is there a +B? What causes this, and how can it be prevented?

Wayne

**Comment by amkozlov** [comment]
Hi Wayne,

`+B` stands for partition-specific branch length scaler in the proportional brlen mode (default). If that is not what you want, you can add `--brlen linked`  to enforce identical brlens across partitions:

https://github.com/amkozlov/raxml-ng/wiki/Input-data#branch-length-linkage

**Comment by wpfeiffer** [comment]
Thanks for the prompt reply :)

On Jul 10, 2024, at 10:27 AM, Oleksiy Kozlov ***@***.******@***.***>> wrote:



Hi Wayne,

+B stands for partition-specific branch length scaler in the proportional brlen mode (default). If that is not what you want, you can add --brlen linked to enforce identical brlens across partitions:

https://github.com/amkozlov/raxml-ng/wiki/Input-data#branch-length-linkage<https://urldefense.com/v3/__https://github.com/amkozlov/raxml-ng/wiki/Input-data*branch-length-linkage__;Iw!!Mih3wA!HwlVGp5hdCqDtov-w-Oth8naYlkERArZJxCg1N_GnwzRqeCvEzUyxuSgFVd8cdgCYecNcMnzDnr7HiJCGrQtjzksfA$>
