### ISSUE TITLE
how many functions are not find in `raxml-ng -h`?

### ISSUE THREAD

**Issue by liamxg** [amkozlov/raxml-ng#188]
Dear @amkozlov,

How many functions are not find in `raxml-ng -h`?

I find that  `--extra` is not list in `raxml-ng -h`.

**Comment by amkozlov** [comment]
If you want to know exactly, please check the source code ;)

https://github.com/amkozlov/raxml-ng/blob/master/src/CommandLineParser.cpp#L12
