### ISSUE TITLE
error

### ISSUE THREAD

**Issue by liamxg** [amkozlov/raxml-ng#190]
Dear @amkozlov,

Could you please help me figure it out, thanks.

line 6: 35533 Bus error: 10

**Comment by amkozlov** [comment]
Please post your hardware configuration and full raxml-ng output, then I will try to help.

**Comment by amkozlov** [comment]
Hm it looks like it could be a hardware error.

Is it reproducible?

If yes, please post your input files and full raxml-ng log.
