### ISSUE TITLE
Confused command line

### ISSUE THREAD

**Issue by liamxg** [amkozlov/raxml-ng#194]
Dear @amkozlov,

If `+F = +FC (empirical)`, `+I ` should =  `+IC`, right?

<img width="640" alt="image" src="https://github.com/user-attachments/assets/1e65aff4-6939-445f-bfc8-c8372c516d81">

**Comment by amkozlov** [comment]
Yes it is a bit inconsistent, partially for historical reasons.

But if I would change the meaning now, eg redefine `+F` = `+FO`, this would generate a lot of confusion.

So I think it will stay like it is, sorry.
