### ISSUE TITLE
 ERROR in SPR round (LIBPLL-3584): Constraint check failed after SPR round!

### ISSUE THREAD

**Issue by jedgold** [amkozlov/raxml-ng#196]
This is a new instance of a previous issue. I'm using raxml-ng-mpi 1.2.2

terminate called after throwing an instance of 'std::runtime_error'
  what():  ERROR in SPR round (LIBPLL-3584): Constraint check failed after SPR round!
[pn011:159113] *** Process received signal ***
[pn011:159113] Signal: Aborted (6)
[pn011:159113] Signal code:  (-6)
[pn011:159113] [ 0] /lib64/libpthread.so.0(+0xf630)[0x2aaaab83c630]
[pn011:159113] [ 1] /lib64/libc.so.6(gsignal+0x37)[0x2aaaaba7f387]
[pn011:159113] [ 2] /lib64/libc.so.6(abort+0x148)[0x2aaaaba80a78]
[pn011:159113] [ 3] /lib64/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x165)[0x2aaaab36fa95]
[pn011:159113] [ 4] /lib64/libstdc++.so.6(+0x5ea06)[0x2aaaab36da06]
[pn011:159113] [ 5] /lib64/libstdc++.so.6(+0x5ea33)[0x2aaaab36da33]
[pn011:159113] [ 6] /lib64/libstdc++.so.6(+0xb53c5)[0x2aaaab3c43c5]
[pn011:159113] [ 7] /lib64/libpthread.so.0(+0x7ea5)[0x2aaaab834ea5]
[pn011:159113] [ 8] /lib64/libc.so.6(clone+0x6d)[0x2aaaabb47b0d]
[pn011:159113] *** End of error message ***

**Comment by amkozlov** [comment]
Please send me all input files and full raxml-ng log, then I will have a look.

Thank you.

**Comment by jedgold** [comment]
I have been unable to reproduce this bug on our system. It may have been a node-specific error, as I got the error 3 times in rapid succession with different input files. If I do get it again I'll reopen this.
