### ISSUE TITLE
Effect of number of threads on raxml.bestModel

### ISSUE THREAD

**Issue by yozeng** [amkozlov/raxml-ng#197]
Hello! I happened to find that the difference in the number of threads has some effect on the results of RAxML (although the random number seed is the same). For example, there are some differences in the specific values in the raxml.bestModel produced by 
`raxml-ng --msa phylip/window_200.phy --model GTR+G --threads 4 --seed 2 --prefix phylip_tree_2/T200` 
and 
`raxml-ng --msa phylip/window_200.phy --model GTR+G --threads 30 --seed 2 --prefix phylip_tree_2/T200`. 

I want to know if this is normal?

**Comment by amkozlov** [comment]
Generally yes, reproducibility can only be guaranteed if random seed, number of threads. and likelihood kernel type (eg AVX) are all identical, see e.g.:

https://academic.oup.com/mbe/article/40/7/msad165/7226636?login=false

**Comment by yozeng** [comment]
I got it, thanks.
