### ISSUE TITLE
The amino acid sequence contains U

### ISSUE THREAD

**Issue by wang748** [amkozlov/raxml-ng#201]
Hello dear developer, below is the error message in the log generated after I run raxml-ng, I would like to know how should I solve this kind of error report?
ERROR: Invalid character in sequence 1 at position 1226400: U
ERROR: Invalid character in sequence 1 at position 2242847: U
ERROR: Invalid character in sequence 1 at position 2418865: U
ERROR: Invalid character in sequence 1 at position 2485088: U
ERROR: Invalid character in sequence 2 at position 1226400: U
ERROR: Invalid character in sequence 2 at position 2242847: U
ERROR: Invalid character in sequence 2 at position 2418865: U
ERROR: Invalid character in sequence 2 at position 2485088: U

**Comment by amkozlov** [comment]
Since `U` does not encode any aminoacid, there must be an error in your alignment or partition file. Please double check.
