### ISSUE TITLE
Add an outgroup option? 

### ISSUE THREAD

**Issue by stamatak** [amkozlov/raxml-ng#29]
To be discussed I think, for pedagogical reasons as this is only a drawing option maybe we should not add this. It adds quite some code without any added value.

**Comment by stamatak** [comment]
Maybe offer this in the application programs and close it here.

**Comment by amkozlov** [comment]
Added this option nevertheless (https://github.com/amkozlov/raxml-ng/commit/ec9f6d2fccc8666fff89b3efe61e227af695af72) since it helps to debug/understand constrained tree inference results.
