### ISSUE TITLE
error: wrong likelihood derivatives

### ISSUE THREAD

**Issue by vmaffei** [amkozlov/raxml-ng#33]
Hello! I am trying to create a tree using raxml-ng on an alignment (99322 taxa and 1285 sites) using 
```sh
./raxml-ng --msa alignment_pfiltered.fasta --model GTR+G4 --search --threads 45 --tree rand{20}
```

Unfortunately, I run into the following error: 
```txt
terminate called after throwing an instance of 'std::runtime_error'
  what():  ERROR in branch lenght optimization: wrong likelihood derivatives
```
Any guidance on what I'm missing or how I might troubleshoot?

**Comment by amkozlov** [comment]
Please try adding `--rate-scalers on` and reduce the number of threads to 8-16. 

If it doesn't help, could you please send me your alignment such that I can reproduce the error?

**Comment by vmaffei** [comment]
Ah great. `--rate-scalers on` did the trick. Thank you for your help and great software!
