### ISSUE TITLE
Uninformative error if partition file ends with a blank line

### ISSUE THREAD

**Issue by TheWhyofFry** [amkozlov/raxml-ng#38]
Hi there

I found a small bug when using partition files that contain a blank line at the end. raxml-ng terminates with an uninformative error message.  While fixing the partition file is fine, it would be helpful if the error message hinted at a malformed partition file.  A blank line in the partition file may not be obvious to the user. Apologies in advance if I missed/omitted something.

> RAxML-NG v. 0.5.0 BETA released on 10.09.2017 by The Exelixis Lab.
> Authors: Alexey Kozlov, Alexandros Stamatakis, Diego Darriba, Tomas Flouri, Benoit Morel.
> Latest version: https://github.com/amkozlov/raxml-ng
> Questions/problems/suggestions? Please visit: https://groups.google.com/forum/#!forum/raxml
> 
> WARNING: This is a BETA release, please use at your own risk!
> 
> RAxML-NG was called as follows:
> 
> raxml-ng-mpi --threads 4 --evaluate --msa ./RT.B.DE.nuc.aligned.fixed.fsa --tree RTIQ.bllenfix.nuc.treefile --model rt.b.de.raxmlng.part --brlen scaled --prefix rt.b.de.nuc.raxml
> 
> Analysis options:
>   run mode: Evaluate tree likelihood
>   start tree(s): user
>   random seed: 1513523851
>   tip-inner: ON
>   pattern compression: ON
>   per-rate scalers: OFF
>   site repeats: OFF
>   branch lengths: ML estimate (proportional)
>   SIMD kernels: AVX2
>   parallelization: PTHREADS (4 threads)
> 
> [00:00:00] Reading alignment from file: ./RT.B.DE.nuc.aligned.fixed.fsa
> [00:00:00] Loaded alignment with 23403 taxa and 1377 sites
> 
> ERROR: h6� 
>

**Comment by amkozlov** [comment]
@TheWhyofFry: thanks for reporting! However, I believe this bug has been already fixed. Could you please try to reproduce it with the latest RAxML-NG v0.5.1:

https://github.com/amkozlov/raxml-ng/releases/tag/0.5.1

Thanks!

**Comment by TheWhyofFry** [comment]
Indeed it does work. Sorry I missed that!

**Comment by amkozlov** [comment]
No problem, thanks for confirmation. Closing this issue.
