### ISSUE TITLE
doesn't compile against any version of libpll

### ISSUE THREAD

**Issue by oistha** [amkozlov/raxml-ng#43]
I can't seem to compile raxml-ng against any version of libpll. I have tried 0.3.2, 0.3.0 and 0.2.0. which version do you compile against ???

libpll provides only one header file. common.h is calling a bunch.
a number of constants aren't defined anywhere in libpll, such as PLLMOD_OPT_MAX_ALPHA

I have tried 0.3.2, 0.3.0 and 0.2.0. which version do you compile against ???

**Comment by amkozlov** [comment]
RAxML-NG  has a bundled version of libpll which is linked via git submodule, please see instructions here:

https://github.com/amkozlov/raxml-ng/wiki/Installation#building-from-source
