### ISSUE TITLE
Scaled BL: BL opt converged to a worse likelihood score

### ISSUE THREAD

**Issue by BenoitMorel** [amkozlov/raxml-ng#48]
When running RAxML-NG on supermuc with `--brlen scaled` option, I get the following error:

```
ERROR: ERROR in branch length optimization (LIBPLL-2240): BL opt converged to a worse likelihood score by -779.593183368444443 units
```

I ran the same search with 11 different seeds and it failed 3 times.
I also happens when I do not use LG4X (but I still have LG4M).
I do not reproduce with the flag  `--blopt nr_safe`.

See `<..>/ALL_1.1.aa/jobs/raxml-ng/lg4m_lg4x_scaled_median/runs/unsafe_runs/raxml_seed2001_rand_scaled_nodes32` on supermuc.

**Comment by amkozlov** [comment]
@BenoitMorel : this should be now fixed in the latest dev (35acc9a)

please test.
