### ISSUE TITLE
HPC raxml-ng-mpi make compilation error

### ISSUE THREAD

**Issue by dhb2128** [amkozlov/raxml-ng#49]
Hi,

I'm currently trying to build the mpi version of raxml.

I got the following error:
```
/usr/bin/ld: /home/dhb13/source/raxml-ng-mpi/localdeps/lib/libpllmodalgorithm_static.a(pllmod_algorithm.c.o): unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [../bin/raxml-ng-mpi] Error 1
make[1]: *** [src/CMakeFiles/raxml_module.dir/all] Error 2
make: *** [all] Error 2
```

I'm using gcc 6.2 and openmpi/3.1.0.

Do you have any suggestions for how to fix this error?

**Comment by amkozlov** [comment]
Seems like your linker is too old, please see:

https://github.com/amkozlov/raxml-ng/wiki/Installation#troubleshooting

and

https://stackoverflow.com/questions/46058050/unable-to-compile-unrecognized-relocation

**Comment by amkozlov** [comment]
@dhb2128 hope this is solved now, please reopen otherwise.
