### ISSUE TITLE
Write a initial date/time string to the log

### ISSUE THREAD

**Issue by terrycojones** [amkozlov/raxml-ng#53]
It would be useful if the log file indicated when the run began. That can be an important part of keeping track of making many trees. It's also very useful in a context where you submit a job to a busy cluster and it takes some time before the job actually begins. Currently it's not possible to look in the log file to see when that was, so one needs to go try to find the job id and then interrogate the scheduling system etc. The `RAxML-NG was called as follows:` line could be change to say `RAxML-NG was called at Thu Nov 15 08:42:57 GMT 2018 as follows:` or similar.

Thanks!

**Comment by amkozlov** [comment]
Please look at the end of the log file, there is a line
```
Analysis started: 13-Nov-2018 15:52:42 / finished: 13-Nov-2018 15:52:43
```
isn't that what you are after?

**Comment by terrycojones** [comment]
Hi @amkozlov Sorry, I should have been clearer. I'd seen the line you mention, but it only appears at the end of the analysis. You can't look at an in-progress log file and tell when the run started.

**Comment by amkozlov** [comment]
Hi @terrycojones,

OK I see your point, just added it to the latest dev (86ad69b). Thanks for suggesting!

Alexey.
