### ISSUE TITLE
raxml-ng stopping with std::runtime_error - error in p-inv optimization

### ISSUE THREAD

**Issue by ephofmann** [amkozlov/raxml-ng#60]
I am working with raxml-ng for the first time, running on a cluster, and my runs stop with the same error multiple times (12 tip tree, ~240 kbp per tip).

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  ERROR in p-inv optimization (LIBPLL-2310): BRENT: initialization failed!
Aborted
```
This occurred first at bootstrap tree #84 with the command `raxml-ng --bootstrap --msa concat.phy --threads 2 --model partition.txt --prefix T2 -log verbose`; I restarted it (exact same command, except different prefix) and it ran (reached convergence at 300 BS). 

Testing the same data with slightly different command: `raxml-ng --all --msa concat.phy --model partition.txt --prefix TEST --seed 2 --threads 8 --bs-metric fbp,tbe -log verbose`, the issue occurred at bootstrap tree #351 on two consecutive runs, and then again when I changed switched `--all` to `--bootstrap` (this time with the same error but additional `terminate called recursively` lines). Also tried the `--rate-scalers on` fix I saw in an earlier closed issue but same result.

Is this a dataset quality issue? Any help is appreciated, thanks!

**Comment by amkozlov** [comment]
@ephofmann thanks for reporting, could you please send me your input files by e-mail?

**Comment by ephofmann** [comment]
Sure thing, just emailed you.

**Comment by amkozlov** [comment]
@ephofmann thanks for reporting & sending the file, this should now be fixed with the latest commit!
