### ISSUE TITLE
include terraphast and libpll in source code distribution

### ISSUE THREAD

**Issue by joelb123** [amkozlov/raxml-ng#61]
I realize that the instructions say to do a recursive git pull, but if you are going to provide a source package with each release, it should really have the dependent libraries in it.

**Comment by amkozlov** [comment]
Those source packages are created automatically by GitHub, and unfortunately there is no way I can add submodules to them. In fact, i cannot even remove those packages! This is one of those weird cases, when everybody knows it's broken, for many years, but apparently github developers do not care:

https://stackoverflow.com/questions/32909389/how-to-creating-github-release-that-includes-submodule

I could add a custom download with full archive (incl. submodules) if you think it would be helpful. However, I'm afraid that having two source packages attached to each release would be even more confusing.

So I can just recommend using `git clone --recursive`, which seems to be the only bulletproof solution atm. As a bonus, you'll get the most recent version with the latest bugfxes :)

**Comment by amkozlov** [comment]
Starting with [v1.0.0](https://github.com/amkozlov/raxml-ng/releases/tag/1.0.0), full source package including submodules will be provided. Unfortunately, I still have to create them manually and still cannot delete the default incomplete packages. Shame on GitHub :bell: :bell: :bell:
