### ISSUE TITLE
"Results files already exist" with --bs-trees 1 and --prefix

### ISSUE THREAD

**Issue by BenoitMorel** [amkozlov/raxml-ng#64]
When running:
```
rm -rf plop
mkdir plop
raxml-ng/bin/raxml-ng --bootstrap --bs-trees 1 --msa msa.fasta --prefix plop --model GTR --thread 1
```
with any alignment, I get the following error:
```
ERROR: Result files for the run with prefix `plop` already exist!
Please either choose a new prefix, remove old files, or add --redo command line switch to overwrite them.
```

I don't reproduce with `--bs-trees 10`.

It seems to come from https://github.com/amkozlov/raxml-ng/blob/dev/src/Options.cpp#L82
The check fails because `outfile_names.bootstrap_trees` is set to '"1"' at https://github.com/amkozlov/raxml-ng/blob/dev/src/CommandLineParser.cpp#L554

Cheers,
Benoit

**Comment by amkozlov** [comment]
You had a file named `1` which messed up my autodetection heuristic (`--bs-trees` accepts both number of replicates OR a file with replicate trees).

This is fixed now, thanks for reporting!
