### ISSUE TITLE
--msa error

### ISSUE THREAD

**Issue by Adelaam** [amkozlov/raxml-ng#68]
Hello,

I am trying to get tree with several polished.fasta sequences, and I am getting the next error:
 Error loading MSA: cannot parse any format supported by RAxML-NG!
Please re-run with --msa-format <FORMAT> and/or --log debug to get more information.

My sequences have several contigs starting cuch us >tig0001. How can I correct this error?

Thank you

**Comment by amkozlov** [comment]
please check your alignment, apparently it is not a valid FASTA file...

**Comment by amkozlov** [comment]
@Adelaam have you managed to fix the problem? if not, could you please post/e-mail your alignment and RAxML-NG command line?

**Comment by lixingguang** [comment]
is there any model for binary?

**Comment by lixingguang** [comment]
is there any updated manual for this version? Because this program making other models available.

**Comment by amkozlov** [comment]
@lixingguang please see here:

https://github.com/amkozlov/raxml-ng/wiki

https://github.com/amkozlov/raxml-ng/wiki/Input-data#evolutionary-model

**Comment by lixingguang** [comment]
@amkozlov, thanks. 
Could I know the detailed name for BIN model?

**Comment by amkozlov** [comment]
@lixingguang it's `--model BIN`, please read the documentation...

**Comment by lixingguang** [comment]
@amkozlov , I know it is the command, I want to know the detail mode name?

**Comment by amkozlov** [comment]
With binary data, only one reversible substitution matrix is possible, since there is just one substitution rate `0 <-> 1`. This could however be combined with non-equal equilibrium state frequencies (`BIN+FO` or `BIN+F`).

Please read:
https://en.wikipedia.org/wiki/Models_of_DNA_evolution
or a standard textbook on computational phylogenetics (Felsenstein, Ziheng Yang...)

@lixingguang and @Adelaam: please use RAxML google group for asking questions about RAxML-NG:

https://groups.google.com/forum/#!forum/raxml

GitHub issues are better suited for bug reports and feature requests. 

Thank you.

**Comment by lixingguang** [comment]
@amkozlov thanks.  You are very kind.
For google, it is not very easy for people in China to access, but still thanks again for all your help.

**Comment by Adelaam** [comment]
Hello Alexey,

Sorry for the late reply. Can I email you my alignment and command line?

**Comment by amkozlov** [comment]
@Adelaam yes. please e-mail them to me!

**Comment by Adelaam** [comment]
'/home/markwilks/raxml-ng_v0.8.1_linux_x86_64/raxml-ng' --msa '/home/markwilks/Desktop/Tree/52184072883polished.fasta' '/home/markwilks/Desktop/Tree/52184147961polised.fasta' '/home/markwilks/Desktop/Tree/52194095915polished.fasta' --model GTR+G

RAxML-NG v. 0.8.1 BETA released on 05.03.2019 by The Exelixis Lab.
Authors: Alexey Kozlov, Alexandros Stamatakis, Diego Darriba, Tomas Flouri, Benoit Morel.
Latest version: https://github.com/amkozlov/raxml-ng
Questions/problems/suggestions? Please visit: https://groups.google.com/forum/#!forum/raxml

WARNING: This is a BETA release, please use at your own risk!

RAxML-NG was called at 28-May-2019 16:00:35 as follows:

/home/markwilks/raxml-ng_v0.8.1_linux_x86_64/raxml-ng --msa /home/markwilks/Desktop/Tree/52184072883polished.fasta /home/markwilks/Desktop/Tree/52184147961polised.fasta /home/markwilks/Desktop/Tree/52194095915polished.fasta --model GTR+G

Analysis options:
  run mode: ML tree search
  start tree(s): random (10) + parsimony (10)
  random seed: 1559055635
  tip-inner: OFF
  pattern compression: ON
  per-rate scalers: OFF
  site repeats: ON
  fast spr radius: AUTO
  spr subtree cutoff: 1.000000
  branch lengths: proportional (ML estimate, algorithm: NR-FAST)
  SIMD kernels: AVX
  parallelization: PTHREADS (2 threads), thread pinning: OFF

[00:00:00] Reading alignment from file: /home/markwilks/Desktop/Tree/52184072883polished.fasta

ERROR: Error loading MSA: cannot parse any format supported by RAxML-NG!
Please re-run with --msa-format <FORMAT> and/or --log debug to get more information.

**Comment by Adelaam** [comment]
[tree.zip](https://github.com/amkozlov/raxml-ng/files/3228299/tree.zip)

**Comment by amkozlov** [comment]
@Adelaam thanks for the files, the sequences in your FASTA file are not aligned, they have different lengths.

please use multiple sequence aligner before running raxml-ng!

**Comment by Adelaam** [comment]
Hi Alexey,

Thank you for your answer.

Maybe I did not understand it properly. I wat to see a tree with my sequences, which I assembled them the novo, than corrected and polished. Now I want to see the tree, I though you can put your sequences and then get the tree, but you say I need to align them, with what? With the reference one?

A
