### ISSUE TITLE
AU test

### ISSUE THREAD

**Issue by univerijung** [amkozlov/raxml-ng#69]
I love this program making other models available.
As stamatak mentioned before, for the AU test I need the per-site log likelihoods. And the command '--tree-constraint' is the same to '-z' in raxmlHPC? I did not find the commands in raxml-ng. Please help me and thanks in advance. 
Jae-Ho.

**Comment by amkozlov** [comment]
Hi @univerijung ,

- per-site log likelihoods printing is not yet available as of RAxML-NG v0.9, I'll add it into the next release (or maybe directly AU test)

- `--tree-constraint` is equivalent to `-g` in RAxML 8.x

- please use [RAxML google group](https://groups.google.com/forum/#!forum/raxml) for asking questions about RAxML-NG:


Best,
Alexey
