### ISSUE TITLE
bootstrapping convergence check (autoMRE etc.)

### ISSUE THREAD

**Issue by amkozlov** [amkozlov/raxml-ng#7]

**Comment by stamatak** [comment]
I wonder if this should not rather be implemented in a separate module and handled via a pyhton script to keep the core raxml-ng code cleaner. I don't see any real advantage in integrating this directly into NG.

**Comment by amkozlov** [comment]
autoMRE implemented

**Comment by amkozlov** [comment]
Just add `--bs-cutoff 0.01`.

Please run `raxml-ng -h` to get further help on command line usage.
