### ISSUE TITLE
How to use the help command (IQ-Tree predictive model is JTT+F+G4)

### ISSUE THREAD

**Issue by CK-X** [amkozlov/raxml-ng#72]
How to use the help command (IQ-Tree predictive model is JTT+F+G4)

I use IQ-Tree to predict the protein sequence model, which shows that the best model is JTT+F+G4. Next I want to use Raxml to build the tree. Here is the command I used, is it correct? Secondly, if I don't pass IQ-Tree prediction model And what kind of command is needed to build the tree directly using Raxml (requirement: publish an article on protein gene family identification)

./raxml-ng --bootstrap 1000 --model JTT+F+G4 --msa mega_pep.fa.phy --threads 4

**Comment by amkozlov** [comment]
Please read RAxML-NG tutorial and wiki:

https://github.com/amkozlov/raxml-ng/wiki/Tutorial

https://github.com/amkozlov/raxml-ng/wiki
