### ISSUE TITLE
Error in raxml

### ISSUE THREAD

**Issue by khuch123** [amkozlov/raxml-ng#75]
On running the following command in R,
alignment.rax.gtr <- raxml(alignment,
                            m="GTRGAMMAIX", # model
                            f="a", # best tree and bootstrap
                            p=1234, # random number seed
                            x=5678, # random seed for rapid bootstrapping
                            N=100, # number of bootstrap replicates
                            file="alignment", # name of output files
                            exec="raxmlHPC-PTHREADS-SSE3", # name of executable
                            threads=20
)
The error is the following:
Error in raxml(alignment, m = "GTRGAMMAIX", f = "a", p = 1234, x = 5678,  : 
  argument 4 matches multiple formal arguments

**Comment by amkozlov** [comment]
Sorry but I can't help here, since this error is coming from your R wrapper and not from RAxML.

Furthermore, please use google group to ask questions about RAxML:
https://groups.google.com/forum/#!forum/raxml
