### ISSUE TITLE
Error in RaxML alignment

### ISSUE THREAD

**Issue by khuch123** [amkozlov/raxml-ng#76]
Yes Sir

I understand it is out of the scope for RaxML but could you please advice as to what could be the workaround, because I cannot work further then.

**Comment by amkozlov** [comment]
Apparently, you misspelled one of the parameters for the `raxml` wrapper funbtion in R  (`p` or `x`). Please check the function definition or your R library documentation. 

Please understand that I can't help you with problems not related to raxml itself, I don't event know what is that R wrapper you are using...
