### ISSUE TITLE
how do I  test with topologies is more reasonable by phyml, raxml and iqtree?

### ISSUE THREAD

**Issue by LiXingguangBrandonStark** [amkozlov/raxml-ng#78]
@stamatak @amkozlov , I use the three software to test the topologies, but all the three are different from each other, how can I know which is the best one? 
I do not access to google, so hope you can image that.

**Comment by amkozlov** [comment]
Well you can re-compute log-likelihood scores using one of the program, and pick a tree with the best score. This is what we did in raxml-ng paper, please read supp. material:

https://academic.oup.com/bioinformatics/article/doi/10.1093/bioinformatics/btz305/5487384/
