### ISSUE TITLE
Compilation error due to a missing CMakeLists.txt

### ISSUE THREAD

**Issue by moravveji** [amkozlov/raxml-ng#79]
Hi,

I am trying to compile raxml-ng v. 0.9.0 for one our cluster users on the Intel Haswell nodes, with CentOS 7.6 OS, using the GCC 6.4.0 and OpenMPI 2.1.2.

During the cmake step, I get the following error:

`CMake Error at libs/CMakeLists.txt:7 (add_subdirectory):
  The source directory
    /data/leuven/sys/x0090231/easybuild/work/RAxML-NG/raxml-ng/libs/pll-modules
  does not contain a CMakeLists.txt file.
`

I have attached my build script, and also the build logs (after trimming paths heavily).

Would you let me know if I am doing something wrong? Otherwise, I will be grateful to have your feedback.

Regards,
Ehsan

**Comment by moravveji** [comment]
Oops ... forgot to attach
[logs.tar.gz](https://github.com/amkozlov/raxml-ng/files/3686376/logs.tar.gz)

**Comment by amkozlov** [comment]
Hi Ehsan,

you have probably downloaded the auto-generated source code archive which does not contain submodules (libpll etc.).

Please use one of the following options:

1. Download package with pre-compiled dependencies: https://github.com/amkozlov/raxml-ng/releases/download/0.9.0/raxml-ng_v0.9.0_linux_x86_64_MPI.zip

2. Clone raxml-ng repo recusively, as described here: https://github.com/amkozlov/raxml-ng/wiki/Installation#building-from-source

Best,
Alexey

**Comment by moravveji** [comment]
@amkozlov : Thanks for the tip. I just tried it, and could easily fetch it all.
