### ISSUE TITLE
alternative parallelization (multiple concurrent tree searches/bootstraps, like in RAxML-MPI)

### ISSUE THREAD

**Issue by amkozlov** [amkozlov/raxml-ng#8]

**Comment by MaximilianStammnitz** [comment]
Hi @amkozlov, wanted to ask if there's already a raxml-ng test version for this intended implementation of concurrent tree searches/bootstraps? I'd be keen to give it a try if so.

Many thanks, Max

**Comment by amkozlov** [comment]
Hi @MaximilianStammnitz, yes there is a test version available here:

https://github.com/amkozlov/raxml-ng/tree/coarse

You can add `--workers N` option where `N` is the desired number of concurrent tree searches. Please note that not everything works in this version yet, eg. MPI+checkpointing (and MPI support in general is not very well tested). I plan to finalize coarse-grain parallelization support in the next few weeks, but of course early adopters/testers are always welcome! :)

**Comment by MaximilianStammnitz** [comment]
Great, many thanks! Happy to try it out and we don't use MPI, so that shouldn't be big deal for now.

Could you possibly also make the linux_x86_64 binary available for this fork? (sorry for my lack of experience with this, hope this would not take too much time).

Cheers, Max

**Comment by amkozlov** [comment]
sure, here you go:

[raxng-coarse.zip](https://github.com/amkozlov/raxml-ng/files/3917590/raxng-coarse.zip)

**Comment by MaximilianStammnitz** [comment]
Thanks, running it now and will report back.

Max

**Comment by amkozlov** [comment]
implemented in the [coarse branch](/amkozlov/raxml-ng/tree/coarse), to be included in raxml-ng 1.0

**Comment by cgjosephlee** [comment]
Sorry, I'm a little confused with different implementations of multi-threading, like **mpi**, **mpi+pthread**, **coarse**, **coarse+mpi** and maybe **coarse+mpi+pthread (?)**.
I have seen improvements on coarse version on single node.
I'm currently running `mpiexec --host s1,s2 -np 2 raxml-ng-coarse --workers 8 --threads 32 --msa aln.fa --model LG+I+F+G4 --bs-trees 500` on two 32-core machines, is this rational? (version 27.10.2019)

**Comment by amkozlov** [comment]
Proper documentation on coarse-grained parallelization is coming soon...

Meanwhile, please read:
https://github.com/amkozlov/raxml-ng/wiki/Parallelization
and in particular:
https://github.com/amkozlov/raxml-ng/wiki/Parallelization#coarse-grained-parallelization-for-short-alignments

This should give you an idea on how many workers to use.
