### ISSUE TITLE
Quick and dirty phylogenetic tree of protein sequences

### ISSUE THREAD

**Issue by mirix** [amkozlov/raxml-ng#80]
Hello,

I have an alignment of highly divergent protein sequences with some 5000 sequences. I would like to derive a quick and dirty phylogenetic tree. 

Online servers do not accept that many sequences whereas parallel codes such as RAXML-NG and IQ-TREE take for ever (over two weeks and counting) on a Xeon hexacore at 3.6 GHz. Whereas others require more than the 16GB of RAM I have.

Is it possible to derive a quick and dirty tree with RAXML-NG? If so, what the command line would be? How long should I expect it to take?

Best,

Miro

**Comment by amkozlov** [comment]
Hi @mirix,

two weeks sounds like a bit too long even for 5000 seqs. Could you please post your log file?

If you need a "quick and dirty" tre, you can use parsimony (`--start --tree pars{1}`), or ML tree from a single starting tree (eg `--search1` or `--search --tree pars{1}`).

Best,
Alexey

**Comment by mirix** [comment]
[T3.raxml.log](https://github.com/amkozlov/raxml-ng/files/3728417/T3.raxml.log)

**Comment by amkozlov** [comment]
Well, you are using a wrong model name:
```
ERROR: ERROR model initialization |PROT| (LIBPLL-5002): Invalid rates symmetry definition: 
```
Please find a list of available protein models here:
https://github.com/amkozlov/raxml-ng/wiki/Input-data#single-model

**Comment by mirix** [comment]
Sorry, I had overwritten the original log file... 

That was the command line:

raxml-ng --msa PDBBind_ali.fasta --model LG --prefix T3 --threads 6 --seed 2

**Comment by amkozlov** [comment]
ok this looks better :)

but could you please post complete log file with the correct model?

**Comment by amkozlov** [comment]
@mirix closing since I never got a correct log file form you. Please reopen if you are still interested in this one.
