### ISSUE TITLE
unrecognized option `--constraint-tree'

### ISSUE THREAD

**Issue by jtklein** [amkozlov/raxml-ng#83]
The doc states that you can use topological constraints. https://github.com/amkozlov/raxml-ng/wiki/Input-data#topological-constraint

However, when I try to use it I get the error: 
raxml-ng: unrecognized option `--constraint-tree'

**Comment by amkozlov** [comment]
@jtklein could it be that you are using a very old version of raxml-ng? I guess this feature was added in v0.6.0.

Otherwise, could you please post full raxml-ng command line?

**Comment by jtklein** [comment]
No, it was the newest version. I was digging around in the source for a bit. The problem is that the parameter for the program is '--tree-constraint'.

So, only the docs need to be changed I guess, where the param is called '--constraint tree'

**Comment by amkozlov** [comment]
You are right, thanks for pointing this out! I fixed the documentation.
