### ISSUE TITLE
BL opt converged to a worse likelihood score 

### ISSUE THREAD

**Issue by jonoave** [amkozlov/raxml-ng#86]
Hello, 

I just encountered an error running raxml-ng:
###
ERROR: ERROR in branch length optimization (LIBPLL-2240): BL opt converged to a worse likelihood score by -0.016206621156243 units terminate called after throwing an instance of 'std::runtime_error'
###

The raxml version is:
RAxML-NG v. 0.9.0git released on 24.05.2019 by The Exelixis Lab.

I found a similar error referenced here https://github.com/amkozlov/raxml-ng/issues/48, but it was stated as solved.

The command was: 
raxml-ng --model LG4X+IC --msa KOG0003.trim.gap.min --threads 2 

Edit to add:
Changed model to LG4M+IC, it ran without any issues.

**Comment by amkozlov** [comment]
Hi @jonoave,

could you please send me your input files and raxml-ng log?

**Comment by jonoave** [comment]
Hi,

Here are the files 
[KOG0003.trim.gap.min.raxml.log](https://github.com/amkozlov/raxml-ng/files/4297571/KOG0003.trim.gap.min.raxml.log)

[KOG0003.trim.gap.txt](https://github.com/amkozlov/raxml-ng/files/4297578/KOG0003.trim.gap.txt)

**Comment by amkozlov** [comment]
Hi @jonoave,

thanks for reporting and sending the input files! 

This bug is now fixed [in the dev branch](https://github.com/amkozlov/raxml-ng/wiki/Installation#building-development-branch).

**Comment by jbruxaux** [comment]
Hi,

I'm having exactly the same problem with version 1.1.0. Most of my gene trees run fine, but two of them fail. I attach one (phy format but renamed as txt), in case it helps. Is it a matter of not enough informative sites inside?

Error message:
terminate called after throwing an instance of 'std::runtime_error'
  what():  ERROR in SPR round (LIBPLL-2240): BL opt converged to a worse likelihood score by -0.080800135211916 units
/var/spool/slurmd/job20331448/slurm_script: line 35: 665385 Aborted                 (core dumped) raxml-ng --threads 16 --bootstrap --bs-trees autoMRE{10000} --bs-cutoff 0.01 --msa /pfs/stor10/projects/projnb10/snic2019-29-3/chloroplast_data/gene_trees/${file}_T2.raxml.rba --model GTR+G --redo --prefix /pfs/stor10/projects/projnb10/snic2019-29-3/chloroplast_data/gene_trees/${file}_T4

[psaI.txt](https://github.com/amkozlov/raxml-ng/files/9470032/psaI.txt)

Thanks for your help!

Jade

**Comment by amkozlov** [comment]
Hi @jbruxaux 

can you please attach full log of this run?

**Comment by jbruxaux** [comment]
Hi @amkozlov 

Here it is!
Thanks for your help!

[raxml_psaI.txt](https://github.com/amkozlov/raxml-ng/files/9493982/raxml_psaI.txt)

**Comment by amkozlov** [comment]
thanks, please try with `--blopt nr_safe`, it should help.

**Comment by jbruxaux** [comment]
Thanks @amkozlov , it worked fine with this option!

**Comment by Christie-ph** [comment]
Hello, 

I have encountered a similar error message when running 
raxml-ng --all --msa sorbus_ISC_85_BSC_92_ms60_edit.phy --model GTR+I+G --tree pars{10} --bs-trees 100 --threads 20 --prefix ms60_GTR_I_G

ERROR: ERROR in SPR round (LIBPLL-2240): BL opt converged to a worse likelihood score by -0.263515570812160 units

/var/spool/slurm/job131322/slurm_script: line 19:  9097 Aborted                 (core dumped) 

while raxml-ng --all --msa sorbus_ISC_85_BSC_92_ms60_edit.phy --model GTR+G --tree pars{10} --bs-trees 100 --threads 20 
ran without any problems. 

Version:
RAxML-NG v. 0.9.0 released on 20.05.2019 by The Exelixis Lab.
Run on Linux HPC cluster.

Could you please help me with this issue?
