### ISSUE TITLE
Branch "coarse" does not build

### ISSUE THREAD

**Issue by ckoe-bccms** [amkozlov/raxml-ng#88]
Hello !

I would like to bring a build failure to your attention. We realize that trying to build a specific branch which has not been released might be unsupported.

A colleague asked me to try to compile the "coarse" branch for him. This appears to be not possible at the moment, the compilation fails with

```
[ 82%] Building CXX object src/CMakeFiles/raxml_module.dir/Tree.cpp.o
[ 83%] Building CXX object src/CMakeFiles/raxml_module.dir/TreeInfo.cpp.o
/home1/ckoe/src/raxml-ng/src/TreeInfo.cpp: In member function ‘double TreeInfo::optimize_params(int, double)’:
/home1/ckoe/src/raxml-ng/src/TreeInfo.cpp:357:78: error: too many arguments to function ‘double pllmod_algo_opt_rates_weights_treeinfo(pllmod_treeinfo_t*, double, double, double, double)’
  357 |                                                           RAXML_PARAM_EPSILON);
      |                                                                              ^
In file included from /home1/ckoe/src/raxml-ng/src/common.h:18,
                 from /home1/ckoe/src/raxml-ng/src/TreeInfo.hpp:4,
                 from /home1/ckoe/src/raxml-ng/src/TreeInfo.cpp:3:
/home1/ckoe/src/raxml-ng/build/localdeps/include/libpll/pllmod_algorithm.h:168:8: note: declared here
  168 | double pllmod_algo_opt_rates_weights_treeinfo (pllmod_treeinfo_t * treeinfo,
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/raxml_module.dir/TreeInfo.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/raxml_module.dir/all] Error 2
make: *** [all] Error 2
```

Complete cmake and make output are attached, [outputs.zip](https://github.com/amkozlov/raxml-ng/files/4475038/outputs.zip). The following commands were used to check the branch out and compile (note that we use a gcc 9.2 from our modules system):
```
git clone --recursive  https://github.com/amkozlov/raxml-ng
cd raxml-ng
git checkout -b coarse origin/coarse
mkdir -p build && cd build
cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ .. > cmake.out 2>&1
make > make.out 2>&1
```

With the same commands/compiler the master branch builds successfully.

Best Regards

**Comment by amkozlov** [comment]
Hi @ckoe-bccms, it seems like submodules have not been updated, please try one of the following:

1. After branch checkout, run 
```
git submodule update --recursive
```
2. Recursively clone the coarse branch directly:
```
git clone --recursive -b coarse https://github.com/amkozlov/raxml-ng raxml-ng-coarse
```

**Comment by ckoe-bccms** [comment]
Hello @amkozlov,

I can confirm that it builds either method you suggested. 

Thank you very much for your help !

**Comment by amkozlov** [comment]
you're welcome, thanks for confirmation!
