### ISSUE TITLE
-DUSE_MPI=ON missing in install.sh included in raxml-ng_v0.9.0_linux_x86_64_MPI.zip

### ISSUE THREAD

**Issue by tardigradus** [amkozlov/raxml-ng#92]
In the release

    raxml-ng_v0.9.0_linux_x86_64_MPI.zip

the file

    install.sh

contains the line 

    cmake ..

Shouldn't this be

    cmake -DUSE_MPI=ON ..

?

**Comment by amkozlov** [comment]
There is no need for this, since MPI release uses a modified CMakeList.txt file, which has USE_MPI enabled by default.
