### ISSUE TITLE
Suggestion - don't search for starting tree when restarting from checkpoint

### ISSUE THREAD

**Issue by davipatti** [amkozlov/raxml-ng#94]
Hello - I just wanted to leave this here as a suggestion.

I have been using raxml on a largish dataset where the starting parsimony tree takes ~4 hours to find. I had to restart the run from a checkpoint, but before continuing from the checkpoint raxml-ng began to look for the starting tree (again).

(It's easily hacked by passing a starting tree with `--tree` which raxml-ng then presumably ignores, and continues using the topology and parameters in the `.ckp` file.)

It seems that raxml-ng should not search for the starting tree again when restarting from a checkpoint.

David

**Comment by amkozlov** [comment]
this is actually how raxml-ng should work now, could you please post your log file?

**Comment by davipatti** [comment]
[FLU.raxml.log](https://gist.github.com/davipatti/f1f03e815dd363e9dc7528946f97f7fc)

**Comment by amkozlov** [comment]
Thanks! I tested with the same version (`0.9.0git released on 26.11.2019`), but cannot reproduce this behavior. Could it be that you copied `.ckp` file to a different machine? raxml-ng will try to reload existing starting trees from `.raxml.startTree` file, but if this file is not present, it will automatically re-generate them from scratch. I suspect this is what happened in your case.

**Comment by davipatti** [comment]
Thanks - you are right!
