### ISSUE TITLE
Error reading newick tree

### ISSUE THREAD

**Issue by cmorganl** [amkozlov/raxml-ng#96]
Hello,

I'm attempting to run `raxml-ng -- evaluate` for a phylogeny I'd like to use with EPA-NG. RAxML-NG is detecting a formatting issue, but I'm not sure if it actually exists.

The error I'm getting is:
```
raxml-ng: /home/connor/bin/raxml-ng/libs/pll-modules/libs/libpll/src/parse_utree.y:500: utree_wraptree: Assertion `inner_index == tip_count + inner_count' failed.
Aborted (core dumped)
```

Here is the log file [NirK.raxml.log](https://github.com/amkozlov/raxml-ng/files/4816774/NirK.raxml.log) and the tree [NirK.FastTree.nwk.txt](https://github.com/amkozlov/raxml-ng/files/4816787/NirK.FastTree.nwk.txt).

The tree was built using FastTree 2.1.10. This error occurs in both the latest release and the version on the master branch. I'm running Ubuntu 18.04. Let me know if you need any more information.

Thank you!

**Comment by amkozlov** [comment]
Hi Connor,

thanks for reporting!

Your tree contains multifurcations (aka polythomies), while raxml-ng requires a strictly bifurcating tree. I will add a respective check and print a  clear error message.

**Comment by cmorganl** [comment]
Oh, excellent - an easy patch! Thanks for figuring that out so quickly, Alexey!

**Comment by amkozlov** [comment]
check added in the coarse branch -> closing
