### ISSUE TITLE
error in ancestral reconstruction

### ISSUE THREAD

**Issue by pnatsi** [amkozlov/raxml-ng#98]
Hi,

I am trying to run the ancestral state reconstruction in raxml-ng, however I get the following error:

raxml-ng: /home/alex/hits/raxng-release/libs/pll-modules/src/optimize/pll_optimize.c:1548: recomp_iterative_multi: Assertion `xguess[p] >= xmin && xguess[p] <= xmax' failed.
raxml-ng: /home/alex/hits/raxng-release/libs/pll-modules/src/optimize/pll_optimize.c:1548: recomp_iterative_multi: Assertion `xguess[p] >= xmin && xguess[p] <= xmax' failed.
raxml-ng: /home/alex/hits/raxng-release/libs/pll-modules/src/optimize/pll_optimize.c:1548: recomp_iterative_multi: Assertion `xguess[p] >= xmin && xguess[p] <= xmax' failed.

Any ideas what could it be? Should I post it in google group better?

Paschalis

**Comment by pnatsi** [comment]
and sometimes I get this error:

raxml-ng: /home/alex/hits/raxng-release/libs/pll-modules/libs/libpll/src/parse_utree.y:366: fill_nodes_recursive: Assertion `index < array_size' failed.
raxml-ng: /home/alex/hits/raxng-release/libs/pll-modules/libs/libpll/src/parse_utree.y:366: fill_nodes_recursive: Assertion `index < array_size' failed.
raxml-ng: /home/alex/hits/raxng-release/libs/pll-modules/libs/libpll/src/parse_utree.y:366: fill_nodes_recursive: Assertion `index < array_size' failed.
raxml-ng: /home/alex/hits/raxng-release/libs/pll-modules/libs/libpll/src/parse_utree.y:366: fill_nodes_recursive: Assertion `index < array_size' failed.

the only difference between the runs is that I used different guide tree with the --tree option

**Comment by pnatsi** [comment]
I managed to run the analyses, however maybe you want to investigate these errors and/or make them more informative for the user.

**Comment by amkozlov** [comment]
Hi Paschalis,

could you please post your input files and raxml log file?

Thanks,
Alexey

**Comment by pnatsi** [comment]
[RealTree.nwk.txt](https://github.com/amkozlov/raxml-ng/files/4836433/RealTree.nwk.txt)
[binary_alignment.fasta.raxml.log.txt](https://github.com/amkozlov/raxml-ng/files/4836434/binary_alignment.fasta.raxml.log.txt)

[binary_alignment.fasta.txt](https://github.com/amkozlov/raxml-ng/files/4836442/binary_alignment.fasta.txt)

**Comment by amkozlov** [comment]
thanks! the problem was due to branch lengths exceeding max limit (100 by default) in your starting tree.

in the latest version, I have added a check for this already.
