### ISSUE TITLE
Old version number reported in command-line help and by `--version`

### ISSUE THREAD

**Issue by mikemc** [amkozlov/raxml-ng#99]
I have installed [version 0.9.0](https://github.com/amkozlov/raxml-ng/releases/download/0.9.0/raxml-ng_v0.9.0_linux_x86_64.zip); however `raxml-ng --version` shows

```
RAxML-NG v. 0.5.1b BETA released on 01.12.2017 by The Exelixis Lab.
Authors: Alexey Kozlov, Alexandros Stamatakis, Diego Darriba, Tomas Flouri, Benoit Morel.
(...)
```
as does `raxml-ng --help`. This seems problematic for users trying to document version numbers in reproducible workflows

**Comment by amkozlov** [comment]
seems like you are still calling the old version. please run
```
which raxml-ng
```
to make sure it points to v0.9.0.

**Comment by mikemc** [comment]
Oops, I thought I had checked this but apparently I hadn't uninstalled the old version. Sorry and thanks!

**Comment by amkozlov** [comment]
no problem, you're welcome!
